### ISSUE TITLE
real word data

### ISSUE THREAD

**Issue by rongtongxueya** [XC-Li/Parallel_CellularAutomaton_Wildfire#1]
Very, very good work, thanks for your open source. Recently, I have been studying using this CA to simulate fire, and I see that these data and parameters seem to be given randomly in your code. I am not sure whether these data and parameters can be replaced by real-world data and how to use real-world data? Could you give me some advice? I just started my research in this direction

**Comment by XC-Li** [comment]
你好，这个程序是根据repo里的那篇pdf论文设计的，所以你可以读一下那篇文章，然后修改相应的参数。
另外，Repo里的Wild_Fire.py是单线程的版本，读起来应该比较简单，可以从那里入手。
